Repository tmpNAWR/thevoca, pull requests merged in 2023-02, with the labels that each got.

#4 Fix(csv): csv파일 불러올때 뷰가 갱신되지 않는 버그를 수정
  GGomVoca/GGomVoca.xcodeproj/project.pbxproj
  GGomVoca/GGomVoca/View/WordListView/CommonView/ImportCSVFileView.swift
  GGomVoca/GGomVoca/View/WordListView/ENWordList/ENWordListView.swift
  GGomVoca/GGomVoca/View/WordListView/FRWordList/FRWordListView.swift
  GGomVoca/GGomVoca/View/WordListView/JPWordList/JPWordListView.swift
  GGomVoca/GGomVoca/View/WordListView/KOWordList/KOWordListView.swift
Labels: bug

#6 Fix(vocabulary): Vocabulary의 Nationality 값을 모두 RawValue 취급하도록 로직을 수정함.
  GGomVoca/GGomVoca/Configuration/UserManager.swift
  GGomVoca/GGomVoca/View/DisplaySplitView/AddVocabularyView.swift
  GGomVoca/GGomVoca/View/DisplaySplitView/Cell/VocabularyCell.swift
  GGomVoca/GGomVoca/View/DisplaySplitView/DisplaySplitView.swift
  GGomVoca/GGomVoca/View/DisplaySplitView/EditVocabularyView.swift
  GGomVoca/GGomVoca/View/WordListView/CommonView/EmptyWordListView.swift
  GGomVoca/GGomVoca/View/WordListView/ENWordList/ENWordListViewModel.swift
  GGomVoca/GGomVoca/View/WordListView/FRWordList/FRWordListViewModel.swift
  GGomVoca/GGomVoca/View/WordListView/KOWordList/KOWordListViewModel.swift
  GGomVoca/GGomVoca/View/WordListView/WordList/AddNewWordView.swift
  GGomVoca/GGomVoca/View/WordListView/WordList/EditWordView.swift
  GGomVoca/GGomVoca/View/WordListView/WordList/WordListViewModel.swift
  GGomVoca/GGomVoca/View/WordListView/WordList/WordsTableView.swift
Labels: fix

#7 Feature/2 order in menu
  GGomVoca/GGomVoca.xcodeproj/project.pbxproj
  GGomVoca/GGomVoca/Repository/CoreDataRepo/CoreDataRepositoryImpl.swift
  GGomVoca/GGomVoca/View/WordListView/CommonView/CustomMenu.swift
  GGomVoca/GGomVoca/View/WordListView/CommonView/ImportCSVFileViewModel.swift
  GGomVoca/GGomVoca/View/WordListView/ENWordList/ENWordListView.swift
  GGomVoca/GGomVoca/View/WordListView/FRWordList/FRWordListView.swift
  GGomVoca/GGomVoca/View/WordListView/JPWordList/JPWordListView.swift
  GGomVoca/GGomVoca/View/WordListView/KOWordList/KOWordListView.swift
  GGomVoca/GGomVoca/View/WordListView/Model/Order.swift
Labels: bug, enhancement
